SkynetLabs/skynet-js

- .prettierignore
- src/client.test.ts
- src/client.ts
- src/download.test.ts
- src/download.ts
- src/index.ts
- src/registry.test.ts
- src/registry.ts
- src/skydb.test.ts
- src/upload.test.ts
- src/utils/url.ts
- yarn.lock
- All client download and `client.get*Url` functions are now `async`.
- Added `getEntryUrlForPortal` standalone method
- Added `getSkylinkUrlForPortal` standalone method
**Note:** To keep the PR lean I didn't address the case of providing a portal URL (e.g. `new SkynetClient("https://siasky.net")`) when we are already on a portal -- that should have no effect, the portal argument should only be for dev testing.
Original PR: https://github.com/NebulousLabs/skynet-js/pull/385
Closes #11
> [BREAKING] Add async portal url init, get*UrlForPortal functions

- package.json
- src/client.ts
- src/crypto.ts
- src/download.test.ts
- src/download.ts
- src/file.ts
- src/integration.test.ts
- src/mysky/index.ts
- src/registry.test.ts
- src/registry.ts
- src/skydb.test.ts
- src/skydb.ts
- src/upload.test.ts
- src/upload.ts
- src/utils/number.ts
- src/utils/options.ts
- src/utils/skylink.test.ts
- src/utils/skylink.ts
- src/utils/string.test.ts
- src/utils/string.ts
- src/utils/url.ts
- src/utils/validation.test.ts
- src/utils/validation.ts
Commit 1:
- [BREAKING] Removed getEntry 'timeout' option.
- Added input validation functions.
- Moved base options to 'utils/options.ts' file.
Commit 2:
- Rework generic 'endpoint' option to be specific for every endpoint (e.g. endpointGetEntry).
Closes #19
> Options rework

- src/index.ts
Just realized that you can't call `mysky.addPermissions()` without the `Permission` class from `skynet-mysky-utils`. I re-export it from `skynet-js` to avoid devs having to set an extra dependency.
> Re-export Permission from skynet-mysky-utils

- src/registry.test.ts
- src/registry.ts
- yarn.lock
The registry had a bug in the transformation to handle uint64 numbers properly. It did not take into account http status codes.
```ts
// Transform the response to add quotes, since uint64 cannot be accurately
// read by JS so the revision needs to be parsed as a string.
transformResponse: function (data) {
```
It throws `Full error: SyntaxError: Unexpected token < in JSON at position 0`
if it receives the following data: 
```html
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty/1.19.3.1</center>
</body>
</html>
```
> Fix getEntry 429 response

- src/mysky/utils.ts
- src/utils/string.ts
- src/utils/url.test.ts
- src/utils/url.ts
Previously, `extractDomainForPortal` and `getFullDomainUrlForPortal` did not work for paths. Now, 
1. `extractDomainForPortal("https://siasky.net", "dac.hns.siasky.net/path/file")` returns `dac.hns/path/file`
2. `getFullDomainUrlForPortal("https://siasky.net", "dac.hns/path/file")` returns `dac.hns.siasky.net/path/file`
3. Both functions have some special handling for localhost
> Make datapath functions work with paths + add datapath tests

- src/client.ts
- src/skydb.ts
- src/utils/options.ts
This PR adds a `customCookie` option to the client options. This allows using accounts. Now I know this is not ideal because of API keys, I thought about adding custom headers but the problem is there it's inconsistent with `customUserAgent`, because it would make that redundant.
This is just a proposal PR. Up for discussion, but I wanted to type it up already.
> Custom Cookie Option

- src/client.ts
- src/download.test.ts
- src/download.ts
- src/integration.test.ts
- [BREAKING] `getFileContent` and `getFileContentHns` no longer return metadata objects.
- [BREAKING] Remove `noResponseMetadata` custom option from download and HNS download methods.
- [BREAKING] `getMetadata` now takes a `CustomGetMetadataOptions` object for custom options.
- [BREAKING] Rename `resolveHns` option `endpointDownloadHnsres` to `endpointResolveHns`.
> [BREAKING] Breaking changes for metadata and download methods

- src/mysky/index.ts
modifies mySky.setDataLink to use skylink v2 version of registry entry format. Could use helper method to reduce code repetition.
> use skylink v2 format for registry entry

- package.json
- src/download.test.ts
- src/skylink/parse.test.ts
- src/skylink/parse.ts
- src/utils/url.test.ts
- utils/testing.ts
- yarn.lock
Fixes CVE concerning `url-parse` and brings `skynet-js` more in line with the standards for URL handling.
> [BREAKING] Add trailing slash to URLs without path

- src/mysky/index.ts
- src/utils/options.ts
- src/utils/validation.test.ts
NOTE: This is a temporary fix, as the SkyDB caching will remove the need for the
setEntryData options to contain getEntry options, and we can change the option
type from CustomSetJSONOptions to CustomSetEntryOptions at that time.
> Fix mySky.setEntryData

- src/client.ts
- src/download.ts
- src/integration.test.ts
- src/registry.ts
- src/utils/string.ts
Resolves some minor nits:
- Avoid unnecessary reassigning of `publicKey` variable. Closes #25 
- Explain `if (opts.subdomain)` conditional in a comment. Closes #26 
- Address followups from "Add async portal url init..." PR. Closes #33  
- Add back "Should upload and download directories" integration test. Closes #64
> Resolve some nits

- package.json
- yarn.lock
Reverts SkynetLabs/skynet-js#192
Husky bump causing potential issues when installing, please revisit and bump if this is not an issue.
```
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ husky install
husky - Git hooks failed to install
spawnSync git ENOENT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
> Revert "Bump husky from 6.0.0 to 7.0.0"

- src/upload.ts
Previously the error returned from tus by skynet-js was too long and technical.
Now we will return the most salient information.
Before:
```
Error: tus: unexpected response while creating upload, originated from request (method: POST, url: https://siasky.xyz/skynet/tus, response code: 413, response text: upload exceeds maximum size: 3580710912 > 1073741824
, request id: n/a)
```
After:
```
Error: upload exceeds maximum size: 26628423680 > 1073741824
```
> Improve tus error

- src/index.ts
- src/skydb.ts
- src/skylink/sia.test.ts
- src/skylink/sia.ts
Previously, `MySky` was being exported as `type`. This meant that Typescript
would complain when trying to use it as a value as in e.g. trying to access the
MySky singleton `MySky.instance`.
> Export MySky as value instead of as type + minor fixes

- jest.config.ts
- src/download.ts
- src/file.ts
- src/index.ts
- src/mysky/connector.ts
- src/mysky/index.ts
- src/mysky/tweak.ts
- src/pin.ts
- src/registry.ts
- src/skydb.test.ts
- src/skydb.ts
- src/skylink/format.ts
- src/skylink/parse.ts
- src/skylink/sia.ts
- src/upload.ts
- src/utils/options.ts
- yarn.lock
- Export new constants in addition to deprecated constants (users would get deprecation warning but the new constants were not available).
- Exports constants `MAX_ENTRY_LENGTH, MYSKY_DOMAIN, MYSKY_DEV_DOMAIN, DEFAULT_SKYNET_PORTAL_URL, URI_HANDSHAKE_PREFIX, URI_SKYNET_PREFIX` and type `EntryData`
- Add some missing documentation
- Update usage of internal constants
> Export new constants in addition to deprecated constants + update internal consts

- src/integration.test.ts
new skyd feature adds "tryfiles" metadata by default to every new upload
> include tryfiles metadata for new release

- jest.config.ts
- src/integration.test.ts
Example test failure: https://github.com/SkynetLabs/skynet-js/pull/298/checks?check_run_id=3693225837
> [NDF] Fix NDF in etag tests: downloading files just uploaded

- src/client.ts
- src/file.ts
- src/index.ts
- src/mysky/encrypted_files.test.ts
- src/mysky/encrypted_files.ts
- src/mysky/index.ts
- Path seeds for directories are now 64 bytes rather than 32.
- Old directory path seeds cannot be passed in to `deriveEncryptedFileSeed`.
- The `ENCRYPTION_PATH_SEED_LENGTH` constant has been removed in favor of `ENCRYPTION_PATH_SEED_DIRECTORY_LENGTH` and `ENCRYPTION_PATH_SEED_FILE_LENGTH`
- Mark `deriveEncryptedFileSeed` and `mySky.getEncryptedFileSeed` as deprecated and point users to
`deriveEncryptedPathSeed` and `mySky.getEncryptedPathSeed` instead. The original function names implied that they
only work on files when they work for folders too.
- Validation has been added to `deriveEncryptedFileKeyEntropy` and
`deriveEncryptedFileTweak` so that they only accept file path seed inputs.
The issue was that path seeds were 64 bytes internally for each directory and then truncated to 32 …
> [BREAKING] Don't truncate the path seeds (for directories only)

- src/download.test.ts
- src/download.ts
- src/upload.ts
There were a couple of bugs preventing tus concat from working.
- The header had to be lowercase.
- `contains` does not exist on strings.
Luckily, the crash from trying to call `contains` doesn't happen in production
because the capitalized header is never found.
> Fix a couple of bugs with tus concat

- integration/upload_download.test.ts
Tries to fix an NDF caused by not having a delay between an upload and a download. This PR just adds a sleep.
> Try to fix NDF in "etag for a resolver skylink" test

- src/client.test.ts
- src/client.ts
- src/download.ts
- src/mysky/utils.ts
- src/registry.ts
- src/upload.ts
- src/utils/string.ts
- src/utils/url.ts
- Makes some changes that were needed for MySky.
- Fixes a bug with portal URL resolution.
- Did a refactor.
- Added tests.
- Add `subdomain` opt to `executeRequest`.
-  This was needed for MySky to access accounts at `account.<portal>`.
- Expose `executeRequest`.
- This was `protected` as there were no known use cases for exposing it until now.
- This is needed for MySky to implement requests to the challenge/response endpoints for accounts.
- Try resolving the portal URL again if the previous attempt failed.
- Previously only a single request for the portal URL would ever be made 
- (the `resolvedPortalUrl` promise was a static variable). 
- Now we retry the request if it failed.
- Refactor `buildRequestUrl`.
- Add some tests for resolving the portal URL, remove an istanbul.
- Add …
> Add `subdomain` opt to `executeRequest` + expose `executeRequest`

- integration/skydb.test.ts
- integration/upload_download.test.ts
- src/client.ts
- src/index.ts
- src/registry.ts
- src/request.ts
- src/upload.ts
- yarn.lock
Previously, methods were returning error messages that said e.g. "Request failed
with status code 429" and we had to drill down into the actual response to see
what the skyd error was.
All methods that make a request now return a descriptive error message based on
the skyd response message.
- Added `ExecuteRequestError` which contains the original Axios error. We now 
throw this on network errors instead of `AxiosError` directly.
- Added `request.ts` file for ExecuteRequestError. I originally tried putting it in 
`client.ts` where it was causing circular dependencies and stuff not being defined
at runtime.
- Also, I fixed a bug where a promise in `uploadLargeFile` was not being
rejected on error.
Review and complete the checklist to ensure that the PR is complete before assigned to an …
> Get the full, descriptive error response returned from skyd

- src/registry.test.ts
- src/registry.ts
Previously, the returned signature was longer than `SIGNATURE_LENGTH`. This is
because `sign` returns the signed message (including the original message) which
was not necessary -- we only need it to return the signature.
In addition to being unnecessary, it was also confusing to have a signature that
was longer than expected.
We are now using `sign.detached`. We already use `verify.detached`.
This doesn't break the test suite because the extra bytes from `sign` 
were being just ignored. The return value for signature is now different though so we label it
a breaking change.
> [Breaking] Use `sign.detached` instead of `sign` to get just the signature

- src/client.test.ts
- src/client.ts
- src/download.ts
- src/request.ts
- src/upload.ts
- src/utils/file.ts
- src/utils/url.test.ts
- src/utils/url.ts
- Rename `addSubdomain` to `addUrlSubdomain` for consistency.
- Use `buildRequestUrl` in more places for simplicity.
- Add tests for `addUrlSubdomain`.
- Added `request.ts` file to move some logic out of `client.ts`, where it was causing circular dependencies and stuff not being defined at runtime.
> Another URL refactor for simplicity/consistency

- package.json
- src/upload.test.ts
- src/upload.ts
- yarn.lock
Previously the client was creating 2 partial uploads of equal size each. The problem with that is that `skyd` will add padding to those uploads if they are not chunkSize aligned. For the second upload that's not a big deal but since we concatenate both, we can't have the first upload contain padding at the end.
What we expect instead is the upload being split up where the first upload is chunkSize-aligned. To achieve that we needed to manually implement part-splitting instead of using the built-in method. 
Here is a simple application that I built on top of the changes:
https://bjftds.hns.siasky.net/
> Fix tus concat and re-enable parallel uploads

- src/upload.ts
Large uploads were failing with a `491` error. This is because of the refactor that changed how URLs are built. The `head` request to get the final metadata of the tus upload was missed in the refactor, and an extraneous
```ts
endpointPath: opts.endpointLargeUpload,
```
was resulting in URLs of the form
```
https://us-va-1.siasky.net/skynet/tus/24581d62dba2a045935680a9c41b0d1b3cd50538/skynet/tus
```
(Note the extra `/skynet/tus` at the end.)
These changes are deployed at:
https://siasky.net/_Aw17anCbXiagDVXQaDktW1m5WuV4FB-S2bk2YdzNM2WZg
(Ignore all the stuff except for the upload form at the top.)
> Fix broken large uploads (tus 491 error)

- .eslintrc.json
- src/client.test.ts
- src/client.ts
- src/download.test.ts
- src/index.ts
- src/mysky/connector.ts
- src/mysky/dac.ts
- src/mysky/index.ts
- src/mysky/tweak.ts
- src/mysky/utils.test.ts
- src/mysky/utils.ts
- src/request.ts
- src/revision_cache.ts
- src/skylink/sia.ts
- src/utils/options.ts
- src/utils/url.test.ts
- src/utils/url.ts
- tsconfig.build.json
- tsconfig.json
- utils/testing.test.ts
- utils/testing.ts
- Implements redirecting the skapp to be on the user's preferred portal, if he has a preferred portal configured.
- Updates some URL utilities and tests based on edge cases that were found when implementing the redirect.
**Note:** Has not been tested yet. Waiting for the corresponding MySky changes, then will test on `alpha` MySky.
```org
Load MySky:
1. SDK opens MySky on the same portal as the skapp.
2. MySky always connects to siasky.net first.
3. MySky tries to get the saved portal preference.
1. If the portal is set, MySky switches to using the preferred portal.
2. If it is not set or we don't have the seed, MySky switches to using
the current portal as opposed to siasky.net.
4. After MySky finishes loading, SDK queries `mySky.getPortalPreference`.
5. If the preferred portal is set …
```
> Preferred portal refresh

- integration/index.ts
- src/client.ts
- src/upload.test.ts
- src/upload.ts
- src/utils/options.ts
Needed to be able to run integration tests against the new pro portal.
Going to merge this into the newly-created `beta` branch, as there are changes in `master` that are not ready for a version publish.
> [NEEDS TESTING] Add option for portal API keys and env var for integration tests

- src/mysky/index.ts
We don't want to fail to initialize MySky or to login if the portal redirect
fails. This can happen if the user entered an invalid portal, and in that case
he wouldn't be able to log in to change the portal.
Also, **this PR temporarily disables the portal redirect** until the autologin
changes in MySky are deployed.
Once this is merged in the `master` branch, we can merge `master` into the
`beta` branch and release a new beta version which includes SkyDB V2 and has
parallel uploads re-enabled. (We can also start working on a new stable
release.)
This commit was confirmed to be working by testing at:
https://bjftds.hns.siasky.net/
I have tested uploading files and directories. I also logged into the test user and 
ran "Test MySky". This now includes new SkyDB v2 tests on MySky.
The …
> Don't throw if portal redirect fails

- src/index.ts
- src/request.test.ts
- src/request.ts
We previously made a change where we were returning a new error type,
`ExecuteRequestError`, from failed network requests instead of `AxiosError`. The
original Axios error was retrievable with `error.originalError`. This was a
break in compatibility for third-party devs who may have come to rely on
`AxiosError` being thrown.
This commit updates `ExecuteRequestError` to be fully compatible with
`AxiosError`. Now this won't be a breaking change.
> Make `ExecuteRequestError` backwards-compatible with `AxiosError`

- .gitignore
- src/mysky/index.ts
Added an if statement to throw an error if both opts.alpha and opts.dev are set.
https://github.com/SkynetLabs/skynet-js/issues/257
> Throws error when passing both dev and alpha options for MySky (#257).

- .github/workflows/checks.yml
Allow optional setting of `SKYNET_JS_INTEGRATION_TEST_SERVER` github secret to switch portal for integration tests.
This is to change the server from default siasky.net to something more stable in times that siasky.net act bumpy.
> use github secret to change integration tests portal

- src/mysky/index.ts
- src/mysky/utils.test.ts
- src/mysky/utils.ts
- [Don't redirect to a preferred portal if we are not on a portal](https://github.com/SkynetLabs/skynet-js/commit/0ef69a5371468151c16aa25dc24d67e00b88830b)
- If we are not on a portal, we can't extract a skapp domain so it is impossible to redirect to a different portal. 
- In this case, we simply set client requests to use the preferred portal.
- [Fix MySky being loaded without API key (always pass custom options)](https://github.com/SkynetLabs/skynet-js/commit/707bb8efdeb4dea3e701c99eb35cdb126661272c)
- MySky can't be loaded without an API key on portals requiring user authentication.
> MySky portal redirect fixes

- CHANGELOG.md
- package.json
- Also run `yarn` in the prepublishOnly script before `yarn build`, to ensure
that the specified dependencies are installed. This is important in case the
developer was on a branch with different dependency versions and forgets to run
`yarn` after leaving that branch.
- ~~All new methods or updated methods have clear docstrings~~
- ~~Testing added or updated for new methods~~
- ~~Verify if any changes impact the WebPortal Health Checks~~
- ~~Approriate documentation updated~~
- ~~Changelog file created~~
> Add short intro to changelog

- integration/skydb.test.ts
- integration/skydb_v2.test.ts
- replace registry entry that pointed to `AABAhNiEqA23bLfXCM4g9uaCYxLT9SzpC6AS-hcM3EZK0A` skylink that can't be accessed any more (lost file)
> replace registry entry with broken test skylink

- CHANGELOG.md
- integration/upload_download.test.ts
- src/client.ts
- src/download.test.ts
- src/download.ts
- src/index.test.ts
- src/pin.test.ts
Due to a peculiarity in axios, `getFileContent` doesn't return binary data
unless you explicitly set the `responseType` option. By default it returns a
string, corrupting data that is actually composed of raw bytes. I feel that this
is such a common case that we should introduce `getFileContentBinary`.
> Add `getFileContentBinary` and `getFileContentBinaryHns`

- CHANGELOG.md
- src/upload.ts
We no longer need to check for whether concat is enabled. The parallel uploads feature should be present on all servers by now.
> Remove initial OPTIONS checking if parallel uploads are supported

- src/upload.ts
I missed this because we added the `Expected parameter 'totalSize' to be greater
than the size of a chunk` check late in review, and I only tested
`chunkSizeMultiplier: 1` after that.
Changes deployed here:
https://bjftds.hns.siasky.net/
Set `chunkSizeMultiplier: 3`.
[Why we don't have integration tests.](https://linear.app/skynetlabs/issue/SKY-304/add-tus-testing-to-integration-tests-health-checks)
Should be no error!
> Fix broken single-chunk uploads when chunkSizeMultiplier > 1

- CHANGELOG-BETA.md
- CHANGELOG.md
- integration/upload_download.test.ts
- src/download.test.ts
- src/download.ts
> Fix getFileContentHns error: skylink comparison

- CHANGELOG.md
- package.json
- scripts/deploy.js
- yarn.lock
I've been using this script privately to deploy the SDK to `skynet-js.hns`.
Figured it made sense to make it an official part of the repository.
Adds a few dependencies but they are all dev-only.
Based on the [`deploy-production`](https://github.com/SkynetLabs/skynet-js/blob/deploy-production/scripts/deploy.js) branch.
Provoked by https://github.com/SkynetLabs/skynet-js/issues/528.
```
$ SKYNET_JS_DEPLOY_SEED="..." node ./scripts/deploy.js
Version: 4.3.0
Downloading HNS domain 'skynet-js' to 'versions.tar'
Untarring 'versions.tar' -> 'versions'
Copying 'bundle' -> 'versions/4.3'
Uploading 'versions' dir
Skylink: AABxT329WcUWVZseqyMwO6cU464cM6SRzx0-RPqKp2nC6w
Updating 'skynet-js' registry entry with skylink
Resolver skylink: sia://AQAnjNAfrW6enU1C7N-TxDjl3kYEkyuu3xm3-uF3BJCN_Q
```
```
$ …
```
> Add deploy script
