src/client.ts
src/mysky/utils.test.ts
src/registry.ts
src/utils/url.ts

Expand `extractDomainForPortal` to work for input URLs in addition to domains. Add tests.

Fix client.extractDomain

---

src/mysky/index.ts
src/skydb.test.ts
src/skydb.ts

Add cachedDataLink option to getJSON

---

CHANGELOG-BETA.md
package.json

Intention is to do a proper stable release later today with Marcin's oversight and continue skylink v2 work in beta stream.

bump to v4.0.6-beta

---

src/download.ts

[BREAKING] Default to subdomain format for HNS URLs.

---

src/download.test.ts
src/download.ts
src/integration.test.ts

Still requires the skylink header in skyd.

Add back headers for getMetadata

---

.github/workflows/daily.yml

- added new servers
- upgraded node to 16
- don't fail pending tests if one fails

add new servers

---

src/client.ts
src/download.test.ts
src/download.ts
yarn.lock

Add range option to download options

---

src/mysky/index.ts
src/registry.ts

Fix setEntryData again

---

README.md
package.json
src/upload.ts
src/utils/url.ts

Update repo to SkynetLabs

---

jest.config.ts
package.json
src/client.test.ts
src/client.ts
src/crypto.test.ts
src/download.test.ts
src/download.ts
src/file.test.ts
src/index.ts
src/integration.test.ts
src/mysky/connector.ts
src/mysky/dac.ts
src/mysky/index.ts
src/registry.test.ts
src/skydb.test.ts
src/skydb.ts
src/skylink/parse.test.ts
src/skylink/sia.test.ts
src/skylink/sia.ts
src/upload.test.ts
src/upload.ts
src/utils/options.test.ts
src/utils/options.ts
src/utils/string.test.ts
src/utils/url.test.ts
src/utils/validation.test.ts
src/utils/validation.ts
yarn.lock

Note: MySky tests will be added separately

Add missing test coverage

---

src/client.ts
src/index.ts
src/integration.test.ts
src/pin.test.ts
src/pin.ts
src/skydb.test.ts
src/skydb.ts
src/utils/validation.ts

Add client.pinSkylink

---

src/upload.ts

See https://github.com/tus/tus-js-client/blob/ba50a8a2c629584273c52dcd133759709ad5e261/docs/api.md#onbeforerequest
Skapp with changes:
https://vg35c6qkg0nbg1ccgk3vlnl4d0ribttehq4d33s8jfog08su04u4cug.siasky.net/

Fix tus cookies and sticky sessions

---

package.json
src/client.ts
src/crypto.ts
src/download.test.ts
src/download.ts
src/integration.test.ts
src/skylink/parse.ts
src/utils/url.ts
types/blakejs/index.d.ts
utils/testing.ts
yarn.lock

Miscellaneous fixes for things that I noticed while porting to skynet-core.

Miscellaneous fixes

---

src/download.ts
src/mysky/connector.ts
src/mysky/index.ts
src/pin.ts
src/registry.ts
src/skydb.ts
src/upload.ts
src/utils/options.ts
src/utils/url.ts

Changes exported constants naming convention.

---

src/mysky/index.ts

Adds a check that MySky developers can use to handle unsupported browsers.

Add mySky browser support check

---

src/mysky/index.ts
src/mysky/utils.ts

Fixes popup size and position when opening the MySky UI window.
- **Example bug:** Opening MySky UI in a small Brave/Chrome window. The MySky UI window was very large.
- Multi-monitor setups.
- Mobile
**Fixed:** https://bjftds.hns.siasky.net/
**Old:** https://cdylhg.hns.siasky.net/

Fix MySky UI window issues

---

src/client.ts
src/file.ts
src/index.ts
src/integration.test.ts
src/mysky/index.ts
src/registry.ts
src/skydb.test.ts
src/skydb.ts

Add entrydata methods

---

.github/workflows/checks.yml
.github/workflows/daily.yml

Just tries to fix the broken Daily CI.
It now returns the correct list of servers: https://github.com/SkynetLabs/skynet-js/pull/314/checks?check_run_id=3864024707

Try to fix Daily CI

---

src/download.ts
utils/testing.test.ts

Also add a test for the testing method `randomUnicodeString`.

[minor] Fix downloadFileHns options

---

CHANGELOG-BETA.md
package.json
src/upload.ts

We need to publish a new version reverting parallel uploads until the chunking is fixed.
I also added a changelog entry for v4.0.18-beta.

Version update to v4.0.19-beta

---

package.json
src/mysky/index.ts

This exposes two new methods on MySky, introduced here https://github.com/SkynetLabs/skynet-mysky/pull/134
See that PR for a more detailed description.
N/A
N/A

Expose signMessage and verifyMessageSignature

---

CHANGELOG-BETA.md
package.json

This PR bumps the version to 4.0.20-beta, adding MySky ID verification methods.
N/A
N/A

Bump version to 4.0.20-beta

---

integration/upload_download.test.ts

Add some simple tests to ensure that [this issue](https://github.com/SkynetLabs/skynet-webportal/issues/1384) is not on the SDK side.

[minor] Add some tests for files and subfiles with spaces in their names

---

integration/upload_download.test.ts

Just a small test to confirm that the `responseType` options works.

[minor] Add test for getFileContents `responseType` option

---

CHANGELOG-BETA.md
package.json

Version update to v4.0.21-beta

---

src/mysky/index.ts
src/upload.test.ts

- Add a test case for parallel uploads
- Better document `getEncryptedPathSeed`

[minor] Some minor improvements

---

integration/index.ts
src/client.ts
src/utils/encoding.ts

Add possibility to authenticate in skynet-js integration tests.

Allow custom cookie in integration tests

---

CHANGELOG-BETA.md
package.json

Release a new beta version which includes SkyDB V2 and has
parallel uploads re-enabled. (We can start working on a new stable
release after this.)
https://github.com/SkynetLabs/skynet-js/blob/b360970390ddc8c2684089a75397e459985679e6/CHANGELOG-BETA.md

Version update to v4.0.26-beta

---

integration/upload_download.test.ts
src/crypto.ts
src/download.ts
src/mysky/utils.ts
src/registry.test.ts

Makes some additions/changes that didn't fit into other PRs so they ended up
stashed.
- Add some internal documentation
- Add getEntryLink test cases
- Remove directory upload subdir in test. It wasn't a proper subdir as Node
doesn't support slashes in filenames.

Make miscellaneous doc and test additions/changes

---

.github/workflows/checks.yml
integration/index.ts
integration/skydb_v2.test.ts
integration/upload_download.test.ts

- [Add skynet API key to CI, use pro server for tests](https://github.com/SkynetLabs/skynet-js/pull/433/commits/1fd8d7a99d51b65a5012fd6d5fd7fe73507124c2), for greater stability in tests.
- [Add delay to integration tests to prevent rate limiting](https://github.com/SkynetLabs/skynet-js/pull/433/commits/56c5961e1470dc6315a2ff70451b1a007d2cabb7)
- [Fix integration tests not passing custom options to new clients](https://github.com/SkynetLabs/skynet-js/pull/433/commits/45a9b223c15a4a8927af351722e0bcb27956bb39)
- [Fix test (hard-coded skylink not working)](https://github.com/SkynetLabs/skynet-js/pull/433/commits/b02a3eab638e2728eb3385cd56119fa6d84e9987)

[CI] Improve integration test stability

---

CHANGELOG-BETA.md
CHANGELOG.md
package.json

Release stable v4 version.
See [changelog](https://github.com/SkynetLabs/skynet-js/blob/18a28bc0942b79b930be5041cc172d774eeb6074/CHANGELOG.md).

Version update to v4.1.0

---

README.md

- Links to `sdk.skynetlabs.com` where appropriate
- Drops context about v2 to v3
- Adds link to introduction workshop for users building with React

Cleanup README for v4 release

---

src/download.ts
src/pin.ts

The docstrings should be more clear than "Skylink striing".

[minor] Update `skylinkUrl` docstrings

---

.gitignore
package.json
yarn.lock

Required for the `staggerPercent` option.

Update @skynetlabs/tus-js-client to v2.4.0

---

CHANGELOG-BETA.md
package.json

```md
- Added `client.getFileContentBinary` and `client.getFileContentBinaryHns` methods for downloading binary data.
- Added `chunkSizeMultiplier` option for large file uploads.
- Added `staggerPercent` option for more efficient uploading of large file uploads.
- Large file uploads now make one less request before starting an upload.
```

Version update to v4.2.0-beta

---

CHANGELOG-BETA.md
CHANGELOG.md
package.json

```md
- Improved performance and stability of integration tests.
```

Version update to v4.2.1-beta

---

CHANGELOG-BETA.md
package.json

```md
- Fixed broken single-chunk uploads when chunkSizeMultiplier > 1.
```

Version update to v4.2.2-beta

---

.github/workflows/ci.yml
src/utils/validation.test.ts

Closes #464.
This is the same pull request as before but with a verified signature.

Add happy cases for functions tested in src/utils/validation.test.ts.

---

.github/workflows/ci.yml

We previously were not running the build script in CI, and potential issues were slipping right past us.

Run the build script in CI

---

CHANGELOG-BETA.md
package.json
yarn.lock

```md
- Removed console output when uploading large files.
```

Version update to v4.2.3-beta

---

CHANGELOG.md
package.json

As far as I know, the community hasn't reported any issues with the improved large file uploads. I think we can prepare to release a new stable version.
```md
- Added `client.getFileContentBinary` and `client.getFileContentBinaryHns` methods for downloading binary data.
- Added `chunkSizeMultiplier` option for large file uploads.
- Added `staggerPercent` option for more efficient uploading of large file uploads.
- Large file uploads now make one less request before starting an upload.
- Improved performance and stability of integration tests.
- Fixed `getFileContentHns` error due to bad skylink comparison. By @parajbs in https://github.com/SkynetLabs/skynet-js/issues/479
```

Version update to v4.3.0

---

.github/workflows/ci.yml

Originally requested here:
https://github.com/SkynetLabs/skynet-js/pull/456#pullrequestreview-958770707
Didn't add `siasky.net` for all runs yet as it's too unstable. I had to add it for PRs from forks though, as they can't access the required repo secrets.

Additionally run `skynet-js` PR CI on `skynetfree` portal
